### ISSUE TITLE
Overhaul UI and pages directory

### ISSUE THREAD

**Issue by ajhenry** [github-community-projects/internal-contribution-forks#73]
## Summary

We received some great designs from `@stvehayes` so we now need to implement them.

The completed designs are in a figma file but an attached SVG can be found in this issue below.

## Team

| Role & Responsibility | Username |
|--|--|
| DRI | @ajhenry |
| Engineering | @sutterj |

## Corresponding Work

```[tasklist]
### Tasks
- [ ] Replace ICF pages router with app directory
- [ ] Create a standard layout page
- [ ] Customize NextAuth login page
- [ ] Fix issue with authentication of JWT being longer than expiration of github token
- [ ] Implement new designs for the rest of the pages and flows
```

## Supporting Documentation

![MVP](https://github.com/github-community-projects/internal-contribution-forks/assets/24923406/21467e24-3ac4-4501-bcb9-e1b22fc1107c)

**Comment by ahpook** [comment]
Closed by #119
